version: "3.8"

services:
  mongodb:
    image: mongo:latest
    volumes:
      - data:/data/db
  server:
    build: ./server
    ports:
      - 1000:1000
    volumes:
      - logs:/app/logs
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongodb
  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - server
volumes:
  data:
  logs: